# SourceHut Build Manifest
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - nodejs
    - yarn
    - hut
sources:
    - https://github.com/lixquid/node-blog-generator
tasks:
    - build: |
          cd *
          cd blog
          git reset --hard origin/master
          cd ..
          yarn install
          yarn build
    - package: |
          cd */out/dist
          tar czvf ../dist.tgz *
          hut pages publish -d blog.lixquid.com ../dist.tgz
